// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmgwynznirelqoetdltg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtZ3d5bnpuaXJlbHFvZXRkbHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMTQ5NTIsImV4cCI6MjA4ODU5MDk1Mn0.MwoqyNEPZrMPCTJ4hvcjETN3ZZKV9hGCmo9W_HLxcpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});